export const Strings = {
    "welcome_to_rushr": "Welcome to RUSHR",
    "home_tag_line": "Welcome to RushR, where connections grow, chapters thrive, and memories are made. Lets get started!",
    "profile_setup_successful": "Profile Setup Successfully",
    "profile_updated_successfull" :"Profile Updated Successfully",
    "go_to_dashboard": "Go to Dashboard",
    "quick_links": "Quick Links",
    "others": "Others",
    "home":"HOME",
    "aboutus":"ABOUT US",
    "features":"FEATURES",
    "testimonials":"TESTIMONIALS",
    "contactus":"CONTACT US",
    "privacypolicy":"PRIVACY POLICY",
    "tnc":"TERMS & CONDITIONS",
    "subscribe_to_our_newsletter": "Subscribe to our Newsletter!",
    "all_rights_reserved": "© 2024 RUSHR. All Rights Reserved.",
    "chapter_list":"Dummy chapters list",
    "students":"Students",
    "name":"Name",
    "school":"School",
    "usertype":"User Type",
    "view_details":"View details",
    "basic_information":"Basic Information",
    "first_name":"First Name",
    "last_name":"Last Name",
    "email":"Email",
    "tags":"Tags",
    "optional":"(optional)",
    "university_name":"University Name",
    "graduation_year":"Graduation Year",
    "major":"Major/Field of Study",
    "preferences":"Preferences",
    "notification_preferences":"Notification Preferences",
    "email_notifications":"Email notifications",
    "privacy_settings":"Privacy Settings",
    "public":"Public",
    "visible_to_everyone":"(visible to everyone)",
    "private":"Private",
    "visible_only_to_chapter_members":"(visible only to chapter members)",
    "astersik":"*",
    "phone":"Phone",
    "bio":"Bio",
    "academic_information":"Academic Information",
    "transform_the_way_your_chapter":"Transform the way your Chapter",
    "communicates_and_grows":"Communicates and Grows",
    "rushr_is_the_first":"RUSHR is the first-ever fraternity and sorority management platform to",
    "plan_events":"plan events, engage members, and sterngthen chapter connections—",
    "seamlessly_and_securely":"seamlessly and securely.",
    "get_on_our_waitlist":"Get on Our Waitlist",
    "members":"Members",
    "chapter":"Chapter",
    "request_a_bid":"Join as Member",
    "history":"HISTORY:",
    "mission":"MISSION:",
    "chapter_rules":"Chapter Rules and Regulations",
    "chapter_activities":"Chapter Activities",
    "request_for_bid":"Request For Bid",
    "connect":"Connect",
    "message":"Message",
    "president":"President",
    "savannah_nguyen":"Savannah Nguyen",
    "chapter_leadership":"Chapter Leadership",
    "year_established":"Year Established",
    "year":"2024",
    "number_of_members":"Number of Members",
    "number_of_followers":"Number of Followers",
    "followers":"Followers",
    "chapter_details":"Chapter Details",
    "login":"Login",
    "welcome_back_to_RUSHR":"Welcome Back to RUSHR",
    "forgot_password":"Forgot Password",
    "dont_have_an_account":"Don’t have an Account?",
    "signup":"Sign Up",
    "select_greek_letters":"Select Greek Letters",
    "chapter_name_preview":"Chapter Name Preview",
    "save":"Save",
    "password_changed_sucessfully":"Password Changed Sucessfully",
    "account_sucessfully_created":"Account Sucessfully Created",
    "chapter_information":"Chapter Information",
    "upload_cover_photo":"Upload Cover Photo",
    "chapter_profile_photo":"Chapter Profile Photo",
    "select_greek_name":"Select Greek Name",
    "chapter_name":"Chapter Name",
    "description":"DESCRIPTION",
    "location":"Location",
    "year_established ":"Year Established",
    "next":"Next",
    "no_chapter_found":"No Chapter Found",
    "seems_like_you_havent_joined_or_created_any_chapter":"Seems Like You havent joined or created any chapter",
    "explore_chapters":"Explore Chapters",
    "long_text":" are you a chapter admin? if you are the leader of your chapter you can request to be admin",
    "other_information":"Other Information",
    "no_members":36,
    "Optional":"(optional)",
    "all_steps":"All steps completed - you&apos,re finished",
    "reset":"Reset",
    "step":"Step",
    "back":"Back",
    "skip":"Skip",
    "users":"Users",
    "chapters":"Chapters",
    "explore":"Explore",
    "message_center":"Message Center",
    "settings":" Settings",
    "dashboard":"Dashboard",
    "Home":"Home",
    "About_Us":"About Us",
    "Features":"Features",
    "Testimonials":"Testimonials",
    "events":"Events",
    "peoples":"Peoples",
    "set_your_password":"Set Your Password",
    "password_text":"Passwords must be at least 8 characters, including one uppercase letter, one number, and one special character.",
    "change_password":"Change Password",
    "acedemic_details":"Share your academic details to connect with members in your area of study.",
    "user_role":"User Role",
    "upload_photo":"Upload Photo",
    "profile_picture_text":"Add a clear and friendly profile picture so others can recognize you.",
    "date_of_birth":"Date of Birth",
    "keywords":"Add keywords that represent you (e.g., leadership, community service, mentoring).",
    "setup_profile_text":"Let’s set up your profile to help you connect with your chapter and community.",
    "setup_profile":"Setup Profile",
    "password_contraint_text":" Passwords must be at least 8 characters, including one uppercase letter, one number, and one special character.",
    "account":"By creating an account you agree to our",
    "TermsnConditions":"Terms & Conditions",
    "already_have_an_account":"Already have an Account?",
    "log_in":"Log In",
    "verify_yourself":"Verify Yourself",
    "enter_your_6_digit_code":"Enter your 6 Digit code",
    "verify":"Verify",
    "registered_email":"Enter your registered email below to reset",
    "your_password":"your password.",
    "request_otp":"Request OTP",
   
    "RUSHR_is_the_first":"RUSHR is the first-ever fraternity and sorority management platform to",
    "Plan_Events":"Plan Events",
    "download_our_app":"DOWNLOAD OUR APP",
    "engage_with_members":"Engage with Members",
    "Scroll_text_2":"Welcome new rushers, foster meaningful connections, and create unforgettable experiences with tools for event scheduling, alumni engagement, and private, organized communication systems.",
    "rushr_is_the_first_ever":"RUSHR Is The First-Ever",
    "fraternity_and_sorority":"Fraternity & Sorority Management Platform",

    "scroll_text_1":"Discover events from other chapters and simplify your own with intuitive planning tools that make scheduling, sharing, and connecting effortless.",
    "strengthen_chapter_connections":"Strengthen Chapter Connections",
    "scroll_text_3":"Strengthen chapter connections with customizable profiles, public event features, and tools to explore and connect with chapters locally and nationwide.",
    "scroll_text_4":"Keep everything at your fingertips with a streamlined, secure platform that brings all your chapter’s essentials into one organized, easily accessible hub.",
    "scroll_text_5":"Effortlessly manage your chapter all in one place. With tools",
    "scroll_text_6":"designed to keep everything running smoothly and securely—giving",
    "scroll_text_7":"you peace of mind and more time to focus on what matters.",
    "streamline_your_chapters_success":"Streamline Your Chapters Success -",
    "connect_organize_empower_with_rushr":"Connect, Organize, Empower with RUSHR",
    "built_for_student_leaders_by":"Built for Student Leaders, by",
    "student_leaders":"Student Leaders",
    "scroll_text_8":" RUSHR is a web application tailored for fraternities and sororities, designed to simplify chapter management.",
    "scroll_text_9":"Empowering student leaders with the resources to manage their chapters as thriving organizations—developing critical problem-solving skills, business expertise, and leadership abilities that last a lifetime.",
    "scroll_text_10":"From event scheduling to alumni engagement, RUSHR empowers students to focus on fostering connections and creating unforgettable experiences.",
    "efficiency":"Efficiency",
    "scroll_text_11":"Spend less time managing and more time participating.",
    "stay_organized":"Stay organized",
    "scroll_text_12":"Keep everything at your fingertips with a streamlined, secure platform that brings all your chapter’s essentials into one organized, easily accessible hub.",
    "community":"Community",
    "scroll_text_13":"Build stronger connections within and beyond your chapter.",
    "growth":"Growth",
    "scroll_text_14":"Develop leadership, organizational, and business skills for life.",
    "how_it_works":"How It Works",
    "getting_started_is":"Getting Started Is",
    "simple_3_Step_process":"Simple 3-Step Process",
    "why_rushr":"Why RUSHR?",
    "interactive_calendar":"Interactive Calendar",
    "scroll_text_15":"Easily schedule, share, and RSVP to events with our intuitive calendar tool.",
    "secure_messaging":"Secure Messaging",
    "scroll_text_16":"Communicate safely and privately with our encrypted messaging system.",
    "centralized_document_hub":"Centralized Document Hub",
    "scroll_text_17":"Organize and access important files in one secure location.",
    "public_event_discovery":"Public Event Discovery",
    "scroll_text_18":"Discover new opportunities and expand your network through public events.",
    "alumni_engagement_tools":"Alumni Engagement Tools",
    "scroll_text_19":"Strengthen alumni relationships with innovative engagement tools.",
    "customizable_profiles":"Customizable Profiles",
    "scroll_text_20":"Personalize your experience with customizable user profiles.",
    "students_feedback":"Students Feedback",
    "ready_to_join_rushr":"Ready to join RUSHR?",
    "organization_chapter":"Organization/Chapter",
    "preferred_method_of_contact":"Preferred method of contact",
    "SUBMIT_YOUR_INQUIRY":"SUBMIT YOUR INQUIRY",
    "PHONE":"PHONE",
    "Phone_No":"(702) 817-4778",
    "EMAIL":"EMAIL",
    "Email_Id":"info@rushr.com",
    "rushr_terms_of_use":"RUSHR TERMS OF USE",
    "Terms":"These terms of use form a binding contract between rushr and you. By using the rushr mobile and web application, you agree to be bound by these terms of use.",
    "Background":"1. Background",
    "Background_a":"a. These Terms of Use apply to all users (Users) of the RushR web and mobile application (RushR Platform). The RushR Platform includes all services, features, and content provided via RushR’s website, mobile app, and associated technology infrastructure.",
    "Background_b":"b. RushR is designed to streamline organization management and foster community engagement for fraternities, sororities, and other collegiate organizations. The platform’s features include chapter management, event scheduling, alumni engagement, and communication tools.",
    "Background_c":"c. The RushR Platform is the property of RushR. It is intended for use by authorized members, including students, alumni, and organizational leaders.",
    "Background_d":"d. RushR reserves the right to modify these Terms of Use at any time. Users are encouraged to periodically review these Terms of Use for updates.",
    "Requirements":"2. Requirements for Use of the RushR Platform",
    "Requirements_a":"a. Compliance with Laws and Policies:",
    "Requirements_a_bullet":"Users must comply with all applicable laws and regulations, as well as RushR’s Privacy Policy and other platform-specific guidelines.",
    "Requirements_b":"b. Respect for Privacy and Intellectual Property:",
    "Requirements_b_bullet":"Users must respect the rights, privacy, and intellectual property of other users.",
    "Requirements_c":"c. Truthful Information:",
    "Requirements_c_bullet":"Users must provide accurate and truthful information when creating an account or using the platform.",
    "Requirements_d":"d. Platform Integrity:",
    "Requirements_d_bullet":"Users must not engage in activities that compromise the security, functionality, or integrity of the RushR Platform or its users' data",
    "Requirements_e":"e. Account Security:",
    "Requirements_e_bullet":"Users are responsible for maintaining the confidentiality of their account credentials and must notify RushR immediately in case of unauthorized account access.",
    "Prohibited_Uses":"3. Prohibited Uses",
    "Prohibited_Uses_a":"a. Engaging in unlawful, harassing, or harmful communications.",
    "Prohibited_Uses_b":"b. Sharing, reselling, or using the RushR Platform for unauthorized commercial purposes.",
    "Prohibited_Uses_c":"c. Misrepresenting your identity or forging communications on the platform.",
    "Prohibited_Uses_d":"d. Accessing or attempting to access data, accounts, or features without authorization.",
    "Prohibited_Uses_e":"e. Uploading, posting, or distributing content that infringes on intellectual property rights or violates privacy laws.",
    "Prohibited_Uses_f":"f. Introducing harmful software, such as viruses or malware, into the platform.",
    "Prohibited_Uses_g":"g. Engaging in activities that disrupt the functionality or accessibility of the RushR Platform for other users.",
    "Account_Creation_and_Verification":"4. Account Creation and Verification",
    "Account_Creation_and_Verification_a":"a. All users must create an account with accurate information.",
    "Account_Creation_and_Verification_b":"b. Upon sign-up, users will be required to verify their email address to activate their account.",
    "Account_Creation_and_Verification_c":"c. Users who fail to verify their accounts within the required time frame will have limited access to platform features until verification is complete.",
    "Data_and_Privacy":"5. Data and Privacy",
    "Data_and_Privacy_a":"a. RushR takes reasonable precautions to protect user data and ensure its integrity. However, no system can guarantee absolute security.",
    "Data_and_Privacy_b":"b. Users must avoid sharing sensitive personal or financial information unless explicitly required and secured by the platform.",
    "Data_and_Privacy_c":"c. RushR reserves the right to monitor, log, and analyze platform activity for security purposes.",
    "Content_and_User_Responsibilities":"6. Content and User Responsibilities",
    "Content_and_User_Responsibilities_a":"a. Content Ownership and Responsibility:",
    "Content_and_User_Responsibilities_b":"b. Restrictions on Commercial Use:",
    "Content_and_User_Responsibilities_c":"c. Community Standards:",
    "Content_and_User_Responsibilities_bullet_a":"Users are responsible for the content they upload or share on the platform. By posting content, users affirm that they have the necessary rights and permissions.",
    "Content_and_User_Responsibilities_bullet_b":"RushR may not be used for unauthorized fundraising, advertising, or commercial activities.",
    "Content_and_User_Responsibilities_bullet_c":"Users must adhere to community guidelines and maintain respectful interactions within the platform.",
    "Violations_and_Enforcement":"7. Violations and Enforcement",
    "Violations_and_Enforcement_a":"a. Reporting Violations:",
    "Violations_and_Enforcement_bullet_a":"Users are encouraged to report any violations of these Terms of Use to RushR support at info@rushr.org.",
    "Violations_and_Enforcement_b":"b. Consequences of Violations",
    "Violations_and_Enforcement_bullet_b":"RushR may suspend or terminate user accounts for violations of these Terms of Use.",
    "Violations_and_Enforcement_c":"c. Legal Action:",
    "Violations_and_Enforcement_bullet_c":"In severe cases, RushR reserves the right to pursue legal action for violations",
    "Disclaimer_of_Liability":"8. Disclaimer of Liability",
    "Disclaimer_of_Liability_a":"a. RushR provides its platform and services on an as-is basis and makes no guarantees regarding uninterrupted access or error-free functionality.",
    "Disclaimer_of_Liability_b":"b. RushR is not liable for any damages resulting from the use or inability to use the platform.",
    "Contact_Information":"9. Contact Information",
    "Contact_Information_line":"For questions or concerns regarding these Terms of Use, please contact RushR at:",
    "Contact_Information_mailid":"info@rushr.org",
    "Contact_Information_website":" www.rushr.org",
    "Acceptance_of_Terms":"10. Acceptance of Terms",
    "Acceptance_of_Terms_line":"By accessing or using the RushR Platform, you acknowledge that you have read, understood, and agree to these Terms of Use.",
    "TNC2":"RushR Fraternity App: Code of Conduct and Compliance Policies",
    "Introduction":"1. Introduction",
    "Introduction_text":"The Rush R Fraternity App is a community-driven platform that enables members, alumni, and organization leaders to collaborate, communicate, and engage in fraternity-related activities. To ensure a positive, inclusive, and ethical environment, this document outlines the Code of Conduct and Compliance Policies for all users. These policies apply to all users, including Students, Alumni, Chapter Members, Organization Admins, and Super Admins. By using the Rush R app, users agree to adhere to these standards. Failure to comply may result in disciplinary actions, including account suspension or permanent removal from the platform.",
    "Code_of_Conduct":"2. Code of Conduct",
    "Respect_for_Others":"2.1 Respect for Others",
    "Respect_for_Others_line":"All users must treat each other with dignity, respect, and fairness. Discriminatory language or behavior, including harassment, hate speech, and bullying, is strictly prohibited. Users are required to foster a safe and inclusive community for all, regardless of race, ethnicity, gender, sexual orientation, religion, or disability.",
    "Integrity_and_Accountability":"2.2 Integrity and Accountability",
    "Integrity_and_Accountability_line":"Users are expected to act with honesty and integrity in all interactions on the platform. Users are accountable for their actions and are responsible for the content they post, messages they send, and interactions they have. Users must avoid any fraudulent, deceptive, or misleading behavior.",
    "Confidentiality":"2.3 Confidentiality",
    "Confidentiality_line":"Users must maintain the confidentiality of sensitive information, such as internal fraternity matters, chapter details, and private posts. Users are prohibited from sharing screenshots of private chats, posts, or fraternity-related materials without consent. Confidential information about fraternity rituals, internal discussions, or financial matters must not be shared outside the fraternity.",
    "Privacy_Data_Protection":"2.4 Privacy & Data Protection",
    "Privacy_Data_Protection_line":"Users must respect the privacy of other users and should not collect, share, or distribute personal information about other members. Users must not access or attempt to access any user data or profile information they do not have permission to view. Users must comply with the Rush R Data Privacy Policy to ensure the protection of personal data.",
    "Compliance_with_Laws_and_Policies":"2.5 Compliance with Laws and Policies",
    "Compliance_with_Laws_and_Policies_line":"Users must adhere to all applicable local, state, and federal laws, as well as university regulations. Illegal activity on the platform, such as threats, extortion, or harassment, will be reported to relevant authorities. Users must comply with university Title IX policies on harassment and discrimination.",
    "Academic_Integrity":"2.6 Academic Integrity (For Students)",
    "Academic_Integrity_line":"Students are encouraged to maintain a focus on academic excellence while engaging in fraternity activities. Users should not post, request, or distribute academic dishonesty materials (e.g., exam answers, homework solutions) via the platform.",
    "Reporting_Violations":"2.7 Reporting Violations",
    "Reporting_Violations_line":"Users are encouraged to report violations of this Code of Conduct, including harassment, abuse, or offensive behavior. Reports can be submitted directly through the app via the 'Report User' button. Reports are confidential, and retaliation against reporters is strictly prohibited.",
    "Enforcement_and_Disciplinary_Actions":"2.8 Enforcement and Disciplinary Actions",
    "Enforcement_and_Disciplinary_Actions_line":"Violations of the Code of Conduct may result in the following actions: Warning, Flagging, Temporary Suspension, or Permanent Ban.",
    "Appeals":"2.9 Appeals",
    "Appeals_line":"Users who are flagged or suspended may submit an appeal via the 'Appeal' button in the user dashboard. Appeals will be reviewed by a Super Admin, and a final decision will be communicated to the user.",
    "Compliance_Policies":"3. Compliance Policies",
    "Posting_and_Content_Guidelines":"3.1 Posting and Content Guidelines",
    "Posting_and_Content_Guidelines_line":"Users must adhere to posting guidelines for public and private posts. Prohibited content includes offensive, inappropriate, and abusive materials. Users can report public and private posts, which will be reviewed by the Super Admin.",
    "Messaging_Policy":"3.2 Messaging Policy",
    "Messaging_Policy_line":"Only users with Active status can message each other. Users must accept message requests from users they do not follow. Prohibited behavior includes sending spam, offensive content, and harassment. Users can report messages for review.",
    "Reporting_Policy":"3.3 Reporting Policy",
    "Reporting_Policy_line":"Users can report inappropriate posts, messages, and member misconduct. Reports are reviewed by the Super Admin, and actions can be taken against the reported user.",
    "Flagging_and_Appeals":"3.4 Flagging and Appeals",
    "Flagging_and_Appeals_line":"Users with multiple reports may be flagged. Flagged users lose access to core features like messaging and posting. Users may appeal their flagged status through the Appeals Dashboard.",
    "Audit_Logs":"3.5 Audit Logs",
    "Audit_Logs_line":"The system maintains audit logs to ensure accountability and compliance. Audit logs track user reports, post interactions, messaging logs, and login history.",
    "Privacy_and_Data_Protection":"3.6 Privacy and Data Protection",
    "Privacy_and_Data_Protection_line":"Rush R complies with data protection laws, including GDPR and CCPA. User data is stored securely and is not shared with third parties unless required by law. Data retention lasts for 12 months after account deactivation.",
    "User_Account_Management":"3.7 User Account Management",
    "User_Account_Management_line":"Users must verify their email to access the platform. Accounts may be suspended for violating policies, and users may request to delete their accounts. Data is erased 30 days after account deletion requests.",
    "Disciplinary_Actions":"4. Disciplinary Actions",
    "Disciplinary_Actions_line":"The Super Admin has the authority to issue warnings, flag users, temporarily suspend accounts, or issue permanent bans for policy violations",
    "Appeals_and_Review_Process":"5. Appeals and Review Process",
    "Appeals_and_Review_Process_line":"Users can submit appeals via the Appeals Dashboard. Super Admins review appeals and notify users of decisions. Approved appeals restore user access, while rejected appeals maintain flagged or suspended status",
    "Policy_Review_and_Updates":"6. Policy Review and Updates",
    "Policy_Review_and_Updates_line":"This policy will be reviewed every 6 months to ensure compliance with industry standards and best practices. Users are notified of policy changes and must accept the updated policy to continue using the platform.",
    "Acknowledgment":"7. Acknowledgment",
    "Acknowledgment_line":"All users must agree to the Code of Conduct and Compliance Policies before using the Rush R platform. By using the platform, users consent to these policies and accept accountability for any violations.",
    "Chapter_Rules":"Chapter Rules/Guidelines",
    "Chapter_description":" Chapter rules and guidelines help outline the expectations and standards for your members. Use this section to clearly define your chapter's policies, values, and code of conduct to ensure a respectful and productive environment.",
    "create_new_chapter":"Create New Chapter",
    "No_students_found_matching_your_search_criteria":"No students found matching your search criteria",
    "error_loading_students":"Error loading students:",
    "Continue":"Continue ",
    "Create_Chapter":"Create Chapter",
    "Profile":"Profile",
    "Logout":"Logout",
    "Loading":"Loading...",
    "preferences_desc": "Provide your chapter details to link your profile to your organization.",
    "Chapter_Created_Successfully":"Chapter Created Successfully",
    "go_to_chapter":"Go to Chapter",
    "view_chapters" :"View Chapter",
    "Profile_preferences_heading":" Profile Preferences",
    "assign_admin":"Assign an Admin",
    "are_you_sure":"Are You Sure?",
    "yes":"Yes",
    "no":"No",
    "upload_new_document":"Upload New Document",
    "document_repository":"Document Repository",
    "upload_file":"Upload File",
    "uploading":"uploading",
    "upload_save":"Upload & Save",
    "Download":"Download",
    "View":"View",
    "Delete":"Delete",
    "Cancel":"Cancel",
    "or_share_a_drive_link":"Or share a drive link",
    "you_want_to_delete_this_document":"You want to delete this document?",
    "upload_success":"File uploaded Succesfully",
    "upload_error" :"Upload failed",
    "First_Name": "First Name" ,
    "Last_Name": "Last Name",
    "f_name":"Mike",
    "l_name" :"Hasi",
    "email_name" :"Email",
    "phone_name" : "Phone",
    "email_id":"abcstudent@edu.com",
    "Pohone_num":"+55 51245412",
    "bio_name":"Bio",
    "bio_data":"Lorem ipsum dolor sit amet consectetur. Pretium sit quis pellentesque amet cursus imperdiet aliquam amet. Montes tincidunt integer et risus orci enim id commodo mattis. Varius in enim ut dolor eu. Cursus pharetra tristique volutpat quis nunc. Id at in sed adipiscing sollicitudin. Tortor eleifend ut et enim eleifend tincidunt. Nisi enim pellentesque enim mattis eleifend sit nibh. Nullam mi risus nec vitae. ",
    "tag_name":"Tag",
    "tag":"<Tag Name>",
    "University_Name": "University Name",
    "Example_University_Name" :"Example University Name",
    "Graduation_Year": "Graduation Year",
    "year":"2022",
    "MajorField_of_Study":"Major/Field of Study",
    "type" :"<Type>",
    "User role": "User role",
    "Notification_Preferences":"Notification Preferences",
    "Email_notifications": "Email notifications",
    "Privacy_Settings" : "Privacy Settings",
    "Public_visible_to_everyone":"Public (visible to everyone)",
    "Joined_name":"Joined",
    "joined_date" :"2024",
    "Chapter_Info" :"Chapter Info",
    "Pi_Kappa_Psy":"Pi Kappa Ps",
    "Followers_number":"200",
    "Followers":"Followers",
    "Connections":"Connections",
    "Connections_number" :"300",
    "massage_button":"MESSAGE",
    "contact_button":"CONTACT",
    "Edit_Profile":"Edit Profile",
    "un_assign_admin":"Un Assign Admin",
    "warning_message" :"Heads up: This action can’t be undone. Still sure?",
    "cancel":"Cancel",
    "Join_as_member":"Join As Member",
    "member" :"Member",
    "admin" :"Admin",
    "view_members":"View Members",
    "all_pending_requests":"All Pending Requests",
    "all_members":"All Members",
    "no_pending_requests":"No Pending Requests available",
    "status":"Status",
    "date_time":"Date & Time",
    "Sign_Up_head":"Sign Up",
    "Set_Up_Your_Chapter":"Set Up Your Chapter",
    "Connect_and_Collaborate":"Connect and Collaborate",
    "signup_step1_text" : "Create an account and verify your chapter with your .edu email.",
    "signup_step2_text" :"Upload rosters, schedule events, and customize your profile.",
    "signup_step3_text":"Start engaging alumni, organizing events, and strengthening your chapter’s communication.",
    "all_pending":"All Pending Requests",
    


    
}